version: '3.9'

services:
  api:
    container_name: go-organa-api
    image: go-organa-api
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    build:
      dockerfile: dev.Dockerfile
      target: dev
    depends_on:
      - postgresdb
    networks:
      - organa-app

  postgresdb:
    image: postgres:15.1-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '1234:5432'
    networks:
      - organa-app

networks:
  organa-app:
    driver: bridge