version: '3.9'

services:
  api:
    container_name: go-organa-api
    image: go-organa-api
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    build:
      dockerfile: dev.Dockerfile
      target: dev